In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [8]:
list = [x for x in range(5)]
list

[0, 1, 2, 3, 4]

In [9]:
arr = [[1, 2, 3, 4, 5],
    [6, 7, 8, 9, 10]]

In [12]:
arr1 = np.array(arr)

In [13]:
type(arr1)

numpy.ndarray

In [24]:
arr[1][3]

9

In [26]:
arr2 = np.array([[11,12,13,14,15],
                [16,17,18,19,20]])

In [27]:
arr2

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [28]:
type(arr2)

numpy.ndarray

In [31]:
arr3 = arr1 * arr2

In [32]:
arr3

array([[ 11,  24,  39,  56,  75],
       [ 96, 119, 144, 171, 200]])

In [37]:
div = arr1 / arr3

In [38]:
div

array([[0.09090909, 0.08333333, 0.07692308, 0.07142857, 0.06666667],
       [0.0625    , 0.05882353, 0.05555556, 0.05263158, 0.05      ]])

In [41]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [70]:
b = np.arange(5)
b

array([0, 1, 2, 3, 4])

In [50]:
ones = np.ones(5)
ones

array([1., 1., 1., 1., 1.])

In [71]:
zeros = np.zeros((6,4))
zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [88]:
eye = np.eye(5,3)
eye

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [66]:
ones.ndim

1

In [72]:
zeros.shape

(6, 4)

In [68]:
div.size

10

In [78]:
odd = np.arange(1,10,2)
odd

array([1, 3, 5, 7, 9])

In [83]:
even = np.arange(0,20,2)
print(even % 2 == 0)
even

[ True  True  True  True  True  True  True  True  True  True]


array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [86]:
linspace = np.linspace(0,10,5)
linspace

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [92]:
eye.reshape((3,5))

array([[1., 0., 0., 0., 1.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0.]])

In [93]:
eye.sum()

3.0

In [95]:
eye.mean()

0.2

In [96]:
np.median(eye)

0.0

In [97]:
eye.std()

0.4000000000000001

In [98]:
arr3

array([[ 11,  24,  39,  56,  75],
       [ 96, 119, 144, 171, 200]])

In [100]:
arr3[-1][-1]

200

In [108]:
set = np.array([1,2,3,4,5])
set[1:3]

array([2, 3])

In [110]:
rand = np.random.rand(4,2)
rand

array([[0.16533707, 0.79328288],
       [0.29593192, 0.99819874],
       [0.22985677, 0.21940758],
       [0.33442091, 0.2452942 ]])

In [113]:
type(rand)

numpy.ndarray

In [117]:
np.random.randint(1,10, (3,3))

array([[5, 9, 9],
       [5, 9, 7],
       [6, 9, 1]])